import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from '@react-email/components'
import * as React from 'react'

interface AdminNotificationEmailProps {
  formType: 'contact' | 'order' | 'newsletter'
  data: Record<string, any>
}

export const AdminNotificationEmail = ({
  formType,
  data,
}: AdminNotificationEmailProps) => (
  <Html>
    <Head />
    <Preview>New {formType} submission - ToyotaParts Direct</Preview>
    <Body style={main}>
      <Container style={container}>
        <Section style={header}>
          <Heading style={logo}>New Submission: {formType.toUpperCase()}</Heading>
        </Section>
        <Section style={content}>
          <Text style={paragraph}>A new form has been submitted on the website:</Text>
          <Section style={dataBox}>
            {Object.entries(data).map(([key, value]) => (
              <div key={key} style={dataRow}>
                <Text style={dataLabel}>{key.replace(/([A-Z])/g, ' $1').toLowerCase()}</Text>
                <Text style={dataValue}>{typeof value === 'object' ? JSON.stringify(value, null, 2) : String(value)}</Text>
              </div>
            ))}
          </Section>
          <Hr style={hr} />
          <Text style={footerText}>
            This email was automatically generated by the ToyotaParts Direct Resend integration.
          </Text>
        </Section>
      </Container>
    </Body>
  </Html>
)

const main = {
  backgroundColor: '#f6f9fc',
  fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
}

const container = {
  backgroundColor: '#ffffff',
  margin: '40px auto',
  maxWidth: '600px',
  borderRadius: '8px',
  overflow: 'hidden',
}

const header = {
  backgroundColor: '#111827',
  padding: '20px',
  textAlign: 'center' as const,
}

const logo = {
  color: '#ffffff',
  fontSize: '18px',
  fontWeight: '700',
  margin: '0',
}

const content = {
  padding: '30px',
}

const paragraph = {
  fontSize: '14px',
  color: '#4b5563',
  margin: '0 0 20px',
}

const dataBox = {
  backgroundColor: '#f9fafb',
  padding: '15px',
  borderRadius: '6px',
}

const dataRow = {
  marginBottom: '10px',
}

const dataLabel = {
  fontSize: '11px',
  fontWeight: '700',
  textTransform: 'uppercase' as const,
  color: '#9ca3af',
  margin: '0',
}

const dataValue = {
  fontSize: '14px',
  color: '#111827',
  margin: '2px 0 0',
}

const hr = {
  borderColor: '#f3f4f6',
  margin: '20px 0',
}

const footerText = {
  fontSize: '12px',
  color: '#9ca3af',
}
